import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lol",
  description: "Generated by create next app",
};
const momentExtended = localFont({
  src: [{
    path: "../public/fonts/MonumentExtended-Regular.woff2",
    weight:"200",
  },

  ],
  variable:"--font-momentExtended"
})
const satoshiBold = localFont({
  src: [{
    path: "../public/fonts/Satoshi-Bold.woff2",
    weight:"200",
  },

  ],
  variable:"--font-satoshiBold"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${momentExtended.variable} ${satoshiBold.variable}`}>{children}</body>
    </html>
  );
}
